#
# Docker setups to test and develop this application.
#
# Build and run all tests via docker-compose up test
test:
  build: .
  volumes:
  - .:/code:z
  working_dir: /code
  entrypoint: /bin/sh
  command: -c 'mvn package'


simple:
  build: .
  volumes:
  - .:/code
  ports:
  - "8080:8080"
  - "8443:8443"
